'use strict';

window.OMAR_SITE = {
  "baseUrl": "https://omar-i9.github.io/omar-i9/",
  "discordPage": "pages/discord.html",
  "release": {
    "version": "v8.1.0 Preview",
    "name": "Portfolio Upgrade",
    "date": "2026-06-18",
    "githubUrl": "https://github.com/Omar-i9/omar-i9",
    "changesAr": [
      "تحميل أولي أخف وظهور متدرج أنعم.",
      "بطاقة آية أصغر وأذكى مع تبديل سلس ونسخ عند فتح التفاصيل.",
      "بحث سريع للروابط وشارات اجتماعية أوضح.",
      "مشاركة وإصدار وديسكورد بنوافذ أخف.",
      "صفحات مشاريع داخلية كبداية لمحفظة v8.1.0."
    ],
    "changesEn": [
      "Lighter first load and smoother staggered reveal.",
      "Smaller smarter ayah card with smooth switching and detail-only copy.",
      "Clearer social badges with smoother card interactions.",
      "Cleaner share, version, and Discord modals.",
      "Internal project pages as a v8.1.0 portfolio preview."
    ]
  },
  "titles": [
    "اهلين تعال كل يوم 👋",
    "Omar Profiles",
    "دامك رجعت شوف الباقي"
  ],
  "heroActions": [
    {
      "id": "github",
      "labelKey": "githubAr",
      "label": "GitHub",
      "icon": "fa-brands fa-github",
      "url": "https://github.com/Omar-i9"
    },
    {
      "id": "share",
      "labelKey": "shareShort",
      "label": "مشاركة",
      "icon": "fa-solid fa-share-nodes",
      "action": "share"
    },
    {
      "id": "instagram",
      "labelKey": "instagramAr",
      "label": "انستجرام",
      "icon": "fa-brands fa-instagram",
      "url": "https://www.instagram.com/omar.a.z3"
    }
  ],
  "socialLinks": [
    {
      "id": "tiktok",
      "group": "social",
      "className": "tk-card",
      "badge": "PUBLIC",
      "badgeType": "vip",
      "icon": "assets/img/brands/tiktok.svg",
      "titleKey": "tiktokAr",
      "title": "تيك توك",
      "handle": "gdmii_33",
      "url": "https://www.tiktok.com/@gdmii_33"
    },
    {
      "id": "snapchat",
      "group": "social",
      "className": "sc-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["featured", "private"],
      "icon": "assets/img/brands/snapchat.svg",
      "titleKey": "snapchatAr",
      "title": "سناب شات",
      "handle": "omar-gdmi",
      "url": "https://www.snapchat.com/add/omar-gdmi"
    },
    {
      "id": "instagram",
      "group": "social",
      "className": "ig-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "badges": ["featured", "public"],
      "icon": "assets/img/brands/instagram.svg",
      "titleKey": "instagramAr",
      "title": "انستجرام",
      "handle": "omar.a.z3",
      "url": "https://www.instagram.com/omar.a.z3"
    },
    {
      "id": "github",
      "group": "dev",
      "className": "github-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "badges": ["official"],
      "icon": "assets/img/brands/github.svg",
      "titleKey": "githubAr",
      "title": "جيت هاب",
      "handle": "Omar-i9",
      "url": "https://github.com/Omar-i9"
    },
    {
      "id": "threads",
      "group": "social",
      "className": "threads-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["private"],
      "icon": "assets/img/brands/threads.svg",
      "titleKey": "threadsAr",
      "title": "ثريدز",
      "handle": "@omar.a.z3",
      "url": "https://www.threads.com/@omar.a.z3"
    },
    {
      "id": "facebook",
      "group": "social",
      "className": "fb-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["private"],
      "icon": "assets/img/brands/facebook.svg",
      "titleKey": "facebookAr",
      "title": "فيسبوك",
      "handle": "3mar.a.z3",
      "url": "https://www.facebook.com/3mar.a.z3"
    },
    {
      "id": "chess",
      "group": "gaming",
      "className": "chess-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["private"],
      "icon": "assets/img/brands/chessdotcom.svg",
      "titleKey": "chessAr",
      "title": "شطرنج",
      "handle": "omar-g4",
      "url": "https://www.chess.com/member/omar-g4"
    },
    {
      "id": "steam",
      "group": "gaming",
      "className": "steam-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["featured", "private"],
      "icon": "assets/img/brands/steam.svg",
      "titleKey": "steamAr",
      "title": "ستيم",
      "handle": "omar_gg33",
      "url": "https://steamcommunity.com/id/omar_gg33/"
    },
    {
      "id": "x",
      "group": "social",
      "className": "x-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "badges": ["public"],
      "icon": "assets/img/brands/x.svg",
      "titleKey": "xAr",
      "title": "اكس",
      "handle": "@OGdmi90694",
      "url": "https://x.com/OGdmi90694"
    },
    {
      "id": "spotify",
      "group": "media",
      "className": "spotify-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "badges": ["public"],
      "icon": "assets/img/brands/spotify.svg",
      "titleKey": "spotifyAr",
      "title": "اسبوتيفاي",
      "handle": "Omar",
      "url": "https://open.spotify.com/user/31zq4egkwu5qt6armgjuvey2tgga"
    },
{
  "id": "rockstar",
  "group": "gaming",
  "className": "rockstar-card",
  "badges": ["official"],
  "icon": "assets/img/brands/rockstar-games.svg",
  "titleKey": "rockstarAr",
  "title": "روكستار",
  "handle": "Omar-G4",
  "url": "https://socialclub.rockstargames.com/member/Omar-G4/games"
},
    {
      "id": "discord",
      "group": "gaming",
      "className": "ds-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "badges": ["private", "contact"],
      "icon": "assets/img/brands/discord.svg",
      "titleKey": "discordAr",
      "title": "ديسكورد",
      "handleKey": "discordNote",
      "handle": "اضغط لفتح البطاقة داخل الموقع",
      "copy": "gdmi_3",
      "action": "discord"
    }
  ],
  "quickCopy": [
    {
      "labelKey": "steamFriendLabel",
      "label": "Steam Friend Code",
      "value": "1586913441",
      "icon": "assets/img/brands/steam.svg"
    },
    {
      "labelKey": "epicGamesLabel",
      "label": "Epic Games",
      "value": "Omar-G4",
      "icon": "assets/img/brands/epicgames.svg"
    },
  {
    "labelKey": "ubisoftLabel",
    "label": "Ubisoft Connect",
    "value": "Omar-G4",
    "icon": "assets/img/brands/ubisoft.svg"
  },
  {
    "labelKey": "eaLabel",
    "label": "EA Account",
    "value": "gdmi3",
    "icon": "assets/img/brands/ea.svg"
  }
  ],
  "projects": [
    {
      "id": "taamenn",
      "titleKey": "projectName",
      "title": "تأمين",
      "descKey": "projectDesc",
      "desc": "بين نبضِ العطاءِ ووقارِ الختام.. يُجمد التطوير ليبقى المشروعُ إرثاً تقنياً، ورمزاً لرحلةٍ اكتملت فخلدت.",
      "url": "https://omar-i9.github.io/taamenn/",
      "pageUrl": "pages/project-taameen.html",
      "liveUrl": "https://omar-i9.github.io/taamenn/",
      "tech": ["HTML", "CSS", "JavaScript", "GitHub Pages"],
      "image": "assets/img/tameen-logo.webp",
      "status": "LEGACY"
    }
  ],
  "ayahs": [
    {
      "text": "﴿لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ﴾",
      "surahAr": "الزمر",
      "surahEn": "Az-Zumar",
      "ayah": 53,
      "refAr": "سورة الزمر: 53",
      "refEn": "Surah Az-Zumar 53",
      "en": "Do not despair of Allah's mercy.",
      "category": "Hope",
      "categoryAr": "الأمل",
      "categoryEn": "Hope",
      "noteAr": "باب الرجاء لا يغلق أمام من يرجع.",
      "noteEn": "The door of hope remains open for sincere return.",
      "tafsirAr": "تذكّر الآية القلب أن رحمة الله أوسع من الذنب والخوف. ليست دعوة للاستهانة بالخطأ، بل دعوة للقيام بعد السقوط والعودة إلى الله بصدق.",
      "tafsirEn": "This verse reminds the heart that Allah's mercy is greater than sin and fear. It does not excuse wrong; it invites a person to rise after falling and return sincerely."
    },
    {
      "text": "﴿قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي يُحْبِبْكُمُ اللَّهُ﴾",
      "surahAr": "آل عمران",
      "surahEn": "Aal-Imran",
      "ayah": 31,
      "refAr": "سورة آل عمران: 31",
      "refEn": "Surah Aal-Imran 31",
      "en": "Say, if you love Allah, follow me; Allah will love you.",
      "category": "Love of Allah",
      "categoryAr": "محبة الله",
      "categoryEn": "Love of Allah",
      "noteAr": "المحبة الصادقة يظهر أثرها في الاتباع.",
      "noteEn": "True love shows itself through following guidance.",
      "tafsirAr": "تجعل الآية محبة الله معنى عمليًا لا مجرد شعور. الطريق إلى محبته يكون باتباع النبي صلى الله عليه وسلم في الإيمان والخلق والعمل.",
      "tafsirEn": "The verse makes love for Allah practical, not only emotional. The path to Allah's love is following the Prophet in faith, character, and action."
    },
    {
      "text": "﴿إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ﴾",
      "surahAr": "يوسف",
      "surahEn": "Yusuf",
      "ayah": 86,
      "refAr": "سورة يوسف: 86",
      "refEn": "Surah Yusuf 86",
      "en": "I only complain of my suffering and grief to Allah.",
      "category": "Sadness",
      "categoryAr": "الحزن",
      "categoryEn": "Sadness",
      "noteAr": "الحزن يجد أمانه عند الله.",
      "noteEn": "Grief is safest when poured before Allah.",
      "tafsirAr": "لا تنكر الآية وجع الإنسان، بل تهذّبه وتوجهه. يعقوب عليه السلام لم يكتم الألم، لكنه جعله بين يدي الله حيث لا يضيع الضعف ولا تخفى الدمعة.",
      "tafsirEn": "The verse does not deny human pain; it gives it direction. Ya'qub did not pretend he was untouched, but placed his grief before Allah, where no tear is unseen."
    },
    {
      "text": "﴿وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ﴾",
      "surahAr": "الشورى",
      "surahEn": "Ash-Shura",
      "ayah": 25,
      "refAr": "سورة الشورى: 25",
      "refEn": "Surah Ash-Shura 25",
      "en": "He is the One who accepts repentance from His servants.",
      "category": "Repentance",
      "categoryAr": "التوبة",
      "categoryEn": "Repentance",
      "noteAr": "الله يفتح باب الرجوع لعباده.",
      "noteEn": "Allah opens the path back for His servants.",
      "tafsirAr": "تبعث الآية طمأنينة في قلب من يريد أن يبدأ من جديد. قبول التوبة من فضل الله، ومعناه أن الماضي لا يحكم على العبد إذا صدق في الرجوع.",
      "tafsirEn": "This verse reassures anyone who wants to begin again. Repentance is accepted by Allah's grace, so the past does not define a servant who returns truthfully."
    },
    {
      "text": "﴿وَيَعْلَمُ مَا فِي الصُّدُورِ﴾",
      "surahAr": "آل عمران",
      "surahEn": "Aal-Imran",
      "ayah": 119,
      "refAr": "سورة آل عمران: 119",
      "refEn": "Surah Aal-Imran 119",
      "en": "He knows what is within the chests.",
      "category": "Quiet pain",
      "categoryAr": "الوجع الصامت",
      "categoryEn": "Quiet pain",
      "noteAr": "ما لا يقال لا يخفى على الله.",
      "noteEn": "What cannot be said is not hidden from Allah.",
      "tafsirAr": "قد يعجز اللسان عن شرح ما في القلب، لكن علم الله يسبق الكلام. في الآية عزاء لمن يحمل وجعًا لا يعرف كيف يصفه للناس.",
      "tafsirEn": "The tongue may fail to explain what the heart carries, but Allah's knowledge comes before speech. This comforts anyone bearing pain they cannot describe."
    },
    {
      "text": "﴿يَعْلَمُ خَائِنَةَ الْأَعْيُنِ وَمَا تُخْفِي الصُّدُورُ﴾",
      "surahAr": "غافر",
      "surahEn": "Ghafir",
      "ayah": 19,
      "refAr": "سورة غافر: 19",
      "refEn": "Surah Ghafir 19",
      "en": "He knows the treachery of the eyes and what the chests conceal.",
      "category": "Trust",
      "categoryAr": "الثقة",
      "categoryEn": "Trust",
      "noteAr": "عدل الله قائم على علم لا يغيب عنه شيء.",
      "noteEn": "Allah's justice rests on knowledge that misses nothing.",
      "tafsirAr": "تعلّم الآية القلب مراقبة الله في الخفاء، وتطمئن المظلوم أن الحقائق المستورة ليست مستورة على الله. لا يضيع صدق ولا يختفي ظلم.",
      "tafsirEn": "The verse teaches awareness of Allah in private and reassures the wronged that hidden truths are not hidden from Him. No sincerity is lost and no injustice disappears."
    },
    {
      "text": "﴿وَابْيَضَّتْ عَيْنَاهُ مِنَ الْحُزْنِ﴾",
      "surahAr": "يوسف",
      "surahEn": "Yusuf",
      "ayah": 84,
      "refAr": "سورة يوسف: 84",
      "refEn": "Surah Yusuf 84",
      "en": "His eyes turned white from grief.",
      "category": "Missing someone",
      "categoryAr": "الشوق والغياب",
      "categoryEn": "Missing someone",
      "noteAr": "الفقد يوجع حتى قلوب الأنبياء.",
      "noteEn": "Loss can ache even in the hearts of prophets.",
      "tafsirAr": "تعرض الآية حزن يعقوب عليه السلام بصدق عميق. الإيمان لا يعني أن الفقد لا يؤلم، بل يعني أن الألم يبقى موصولًا بالصبر والرجاء.",
      "tafsirEn": "The verse shows Ya'qub's grief with deep honesty. Faith does not mean loss stops hurting; it means the hurt remains tied to patience and hope."
    },
    {
      "text": "﴿إِنِّي لَأَجِدُ رِيحَ يُوسُفَ﴾",
      "surahAr": "يوسف",
      "surahEn": "Yusuf",
      "ayah": 94,
      "refAr": "سورة يوسف: 94",
      "refEn": "Surah Yusuf 94",
      "en": "I can smell the scent of Yusuf.",
      "category": "Missing someone",
      "categoryAr": "الشوق والغياب",
      "categoryEn": "Missing someone",
      "noteAr": "بعد طول الغياب قد يفتح الله باب اللقاء.",
      "noteEn": "After long absence, Allah can open a door to reunion.",
      "tafsirAr": "في الآية لحظة رجاء بعد سنين من الانتظار. تذكّر أن ما انقطع في نظر الناس قد يبقى محفوظًا عند الله حتى يحين وقته.",
      "tafsirEn": "This is a moment of hope after years of waiting. It reminds us that what seems cut off to people may remain preserved with Allah until its time arrives."
    },
    {
      "text": "﴿وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ﴾",
      "surahAr": "ق",
      "surahEn": "Qaf",
      "ayah": 16,
      "refAr": "سورة ق: 16",
      "refEn": "Surah Qaf 16",
      "en": "We are nearer to him than his jugular vein.",
      "category": "Nearness to Allah",
      "categoryAr": "القرب من الله",
      "categoryEn": "Nearness to Allah",
      "noteAr": "الله أقرب بعلمه وإحاطته من كل قريب.",
      "noteEn": "Allah is nearer in knowledge and care than any nearness.",
      "tafsirAr": "تؤنس الآية القلب بأن الله يعلم وساوسه وضعفه وحاجته. هذا القرب يربّي المراقبة، ويمنح الوحيد شعورًا أنه ليس متروكًا.",
      "tafsirEn": "The verse comforts the heart: Allah knows its whispers, weakness, and need. This nearness builds awareness and tells the lonely they are not abandoned."
    },
    {
      "text": "﴿إِنَّ رَبِّي قَرِيبٌ مُّجِيبٌ﴾",
      "surahAr": "هود",
      "surahEn": "Hud",
      "ayah": 61,
      "refAr": "سورة هود: 61",
      "refEn": "Surah Hud 61",
      "en": "My Lord is near and responsive.",
      "category": "Dua",
      "categoryAr": "الدعاء",
      "categoryEn": "Dua",
      "noteAr": "الدعاء يصل إلى رب قريب مجيب.",
      "noteEn": "Du'a reaches a Lord who is near and responsive.",
      "tafsirAr": "تقرب الآية معنى الدعاء من القلب: ليس بين العبد وربه مسافة تعجز الصادق. الإجابة تكون بحكمة الله، لكنها تبدأ بعلم وسمع وقرب.",
      "tafsirEn": "The verse brings prayer close to the heart: no distance blocks a sincere servant from the Lord. Response comes with Allah's wisdom, beginning with His knowledge, hearing, and nearness."
    },
    {
      "text": "﴿رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي﴾",
      "surahAr": "القصص",
      "surahEn": "Al-Qasas",
      "ayah": 16,
      "refAr": "سورة القصص: 16",
      "refEn": "Surah Al-Qasas 16",
      "en": "My Lord, I have wronged myself, so forgive me.",
      "category": "Repentance",
      "categoryAr": "التوبة",
      "categoryEn": "Repentance",
      "noteAr": "أصدق التوبة تبدأ بالاعتراف.",
      "noteEn": "The truest repentance begins with admission.",
      "tafsirAr": "هذا دعاء اعتراف بلا تبرير. فيه أدب العبد حين يرى تقصيره، فيرجع إلى الله طالبًا المغفرة لا باحثًا عن أعذار تخفي الحقيقة.",
      "tafsirEn": "This is a prayer of admission without excuse. It shows the servant seeing their fault and turning to Allah for forgiveness instead of hiding behind justifications."
    },
    {
      "text": "﴿ثُمَّ تَابَ عَلَيْهِمْ لِيَتُوبُوا﴾",
      "surahAr": "التوبة",
      "surahEn": "At-Tawbah",
      "ayah": 118,
      "refAr": "سورة التوبة: 118",
      "refEn": "Surah At-Tawbah 118",
      "en": "Then He turned to them so they could repent.",
      "category": "Comfort",
      "categoryAr": "المواساة",
      "categoryEn": "Comfort",
      "noteAr": "حتى التوبة توفيق من الله.",
      "noteEn": "Even repentance is a gift from Allah.",
      "tafsirAr": "تبيّن الآية أن رجوع العبد يبدأ بلطف من الله يفتح له الباب. من وجد في قلبه رغبة في التوبة فليحمد الله، فهي علامة حياة لا علامة يأس.",
      "tafsirEn": "The verse shows that a servant's return begins with Allah gently opening the door. If the heart wants repentance, that desire is a sign of life, not despair."
    },
    {
      "text": "﴿سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا﴾",
      "surahAr": "مريم",
      "surahEn": "Maryam",
      "ayah": 96,
      "refAr": "سورة مريم: 96",
      "refEn": "Surah Maryam 96",
      "en": "The Most Merciful will appoint love for them.",
      "category": "Comfort",
      "categoryAr": "المواساة",
      "categoryEn": "Comfort",
      "noteAr": "الله يزرع الود لعباده الصالحين.",
      "noteEn": "Allah can place love for His righteous servants.",
      "tafsirAr": "تمنح الآية راحة لمن يخاف الجفاء أو الوحدة. القبول الحقيقي من الله، وهو قادر أن يجعل للعبد أثرًا طيبًا ومحبة نقية بين القلوب.",
      "tafsirEn": "The verse comforts anyone afraid of coldness or isolation. True acceptance is from Allah, and He can place a gentle trace and sincere love for a servant among hearts."
    },
    {
      "text": "﴿وَأَلْقَيْتُ عَلَيْكَ مَحَبَّةً مِّنِّي﴾",
      "surahAr": "طه",
      "surahEn": "Ta-Ha",
      "ayah": 39,
      "refAr": "سورة طه: 39",
      "refEn": "Surah Ta-Ha 39",
      "en": "I cast upon you love from Me.",
      "category": "Love of Allah",
      "categoryAr": "محبة الله",
      "categoryEn": "Love of Allah",
      "noteAr": "المحبة من أعظم عطايا الله.",
      "noteEn": "Love from Allah is among the greatest gifts.",
      "tafsirAr": "تذكر الآية نعمة خاصة على موسى عليه السلام، وفيها معنى لطيف: القبول والمحبة ليستا بيد الناس وحدهم، بل يضعهما الله حيث يشاء.",
      "tafsirEn": "The verse recalls a special favor upon Musa. It carries a tender meaning: acceptance and love are not in people's hands alone; Allah places them where He wills."
    },
    {
      "text": "﴿فَصَبْرٌ جَمِيلٌ﴾",
      "surahAr": "يوسف",
      "surahEn": "Yusuf",
      "ayah": 18,
      "refAr": "سورة يوسف: 18",
      "refEn": "Surah Yusuf 18",
      "en": "So patience is most fitting.",
      "category": "Patience",
      "categoryAr": "الصبر",
      "categoryEn": "Patience",
      "noteAr": "الصبر الجميل يحفظ القلب من الانكسار المر.",
      "noteEn": "Beautiful patience protects the heart from bitter collapse.",
      "tafsirAr": "الصبر الجميل ليس برودًا ولا إنكارًا للألم، بل ثبات بلا شكوى تعترض على الله. هو أن يمسك الإنسان قلبه حتى تمر العاصفة ولا يضيع إيمانه فيها.",
      "tafsirEn": "Beautiful patience is not coldness or denial of pain. It is steadiness without objecting to Allah: holding the heart through the storm without losing faith."
    },
    {
      "text": "﴿وَلَا تَهِنُوا وَلَا تَحْزَنُوا﴾",
      "surahAr": "آل عمران",
      "surahEn": "Aal-Imran",
      "ayah": 139,
      "refAr": "سورة آل عمران: 139",
      "refEn": "Surah Aal-Imran 139",
      "en": "Do not weaken and do not grieve.",
      "category": "Inner peace",
      "categoryAr": "السكينة",
      "categoryEn": "Inner peace",
      "noteAr": "الحزن لا يعني نهاية الطريق.",
      "noteEn": "Grief does not mean the road is over.",
      "tafsirAr": "تنهى الآية عن الضعف الذي يجعل الحزن قائدًا للحياة. الألم شعور بشري، لكن المؤمن يتعلم ألا يتحول حزنه إلى استسلام أو فقدان للثقة بالله.",
      "tafsirEn": "The verse warns against weakness that lets grief lead life. Pain is human, but a believer learns not to let sadness become surrender or loss of trust in Allah."
    }
  ],
  "translations": {
    "ar": {
      "heroName": "عُـمَر | Omar",
      "heroDesc": "دامك دخلت كمل معروفك وشوف الباقي..!",
      "langHint": "تغيير اللغة",
      "ayahPill": "آية",
      "ayahHint": "اضغط لعرض تفاصيل الآية",
      "showAyah": "إظهار الآية",
      "hideAyah": "إخفاء الآية",
      "socialLinksTitle": "روابط التواصل",
      "instagramAr": "انستجرام",
      "snapchatAr": "سناب شات",
      "tiktokAr": "تيك توك",
      "facebookAr": "فيسبوك",
      "threadsAr": "ثريدز",
      "githubAr": "جيت هاب",
      "chessAr": "شطرنج",
      "steamAr": "ستيم",
      "twitchAr": "تويتش",
      "xAr": "اكس",
      "spotifyAr": "اسبوتيفاي",
      "kickAr": "كيك",
      "discordAr": "ديسكورد",
      "discordNote": "اضغط لفتح البطاقة داخل الموقع",
      "shareShort": "مشاركة",
      "privacyPublic": "عام",
      "privacyPrivate": "خاص",
      "quickCopyTitle": "نسخ سريع",
      "steamFriendLabel": "Steam Friend Code",
      "epicGamesLabel": "Epic Games",
      "copyBtn": "نسخ",
      "copied": "تم النسخ ✓",
      "projectTitle": "مشروع؟",
      "projectTitle2": "مشروع نسخه تجريبية",
      "projectTitle3": "قد يستغرق وقت لتحميل الصفحة لاول مرة",
      "projectDesc5": "لوحة تحكم حية لسيارة كهربائية — فيزياء بطارية ومحرك حقيقية، WebSocket، HUD احترافي.",
      "projectName": "تأمين",
      "projectDesc": "بين نبضِ العطاءِ ووقارِ الختام.. يُجمد التطوير ليبقى المشروعُ إرثاً تقنياً، ورمزاً لرحلةٍ اكتملت فخلدت.",
      "footerLine1": "الفولو <em>ما بكهربك</em>",
      "footerBrand": "عُـمَر | Omar",
      "footerText1": "جميع الحقوق غير محفوظة © 2026",
      "footerText2": "بتعرف انه كل هاد شغل ايدي؟",
      "shareTitle": "بوابة المشاركة",
      "shareText": "امسح الكود أو شارك الرابط مباشرة",
      "shareCopy": "نسخ",
      "shareSend": "إرسال رابط صفحاتي",
      "sharePreviewTitle": "صفحات عمر",
      "sharePreviewText": "كل حساباتي ومشاريعي وأكواد اللعب بمكان واحد.",
      "shareNativeTitle": "صفحات عمر | Omar Profiles",
      "shareNativeText": "صفحة عمر: روابط التواصل، المشاريع، وأكواد اللعب في مكان واحد.",
      "shared": "تم فتح المشاركة ✓",
      "pageTitle": "Omar Profiles",
      "ariaBtn": "تبديل اللغة إلى الإنجليزية",
      "profileKicker": "نبذة سريعة",
      "profileBio": "طالب توجيهي 2009، هندسة كهربائية سيارات، وبحاول أطلع من السنة بعقلي كامل.",
      "statusSleeping": "نائم",
      "statusBusy": "مشغول",
      "statusOnline": "متصل",
      "statusCoding": "يبرمج",
      "statusGaming": "يلعب",
      "copyAyah": "نسخ الآية",
      "ayahCopied": "تم نسخ الآية ✓",
      "versionLabel": "الإصدار",
      "lowPowerOn": "تم تفعيل الوضع الخفيف للجهاز",
      "newAyah": "آية جديدة",
      "badgeFeatured": "مفضل",
      "badgePublic": "عام",
      "badgePrivate": "خاص",
      "badgeOfficial": "رسمي",
      "badgeContact": "تواصل",
      "versionGithub": "GitHub",
      "closeModal": "إغلاق",
      "shareWhatsApp": "واتساب",
      "shareInstagram": "إنستجرام",
      "shareSnapchat": "سناب شات",
      "shareFallbackCopied": "تم نسخ الرابط، الصقه في التطبيق المناسب",
      "shareWhatsAppText": "شوف صفحة عمر: روابط التواصل والمشاريع والأكواد في مكان واحد.",
      "projectVisit": "زيارة المشروع",
      "projectBack": "رجوع للموقع",
      "projectTech": "التقنيات",
      "projectStatus": "الحالة",
      "projectTaameenSummary": "مشروع تأمين محفوظ كإرث تقني خفيف ضمن رحلة عمر.",
      "projectEvSummary": "لوحة حية لتجربة بيانات سيارة كهربائية مع مؤشرات مباشرة.",
      "projectDetails": "تفاصيل المشروع",
      "rockstarGames": "Rockstar Games",
      "ubisoft": "Ubisoft",
      "ea": "Electronic Arts"
    },
    "en": {
      "heroName": "Omar | عُـمَر",
      "heroDesc": "Since you came in, keep going and check the rest..!",
      "langHint": "Change language",
      "ayahPill": "Ayah",
      "ayahHint": "Tap to view tafsir",
      "showAyah": "Show ayah",
      "hideAyah": "Hide ayah",
      "socialLinksTitle": "Social Links",
      "instagramAr": "Instagram",
      "snapchatAr": "Snapchat",
      "tiktokAr": "TikTok",
      "facebookAr": "Facebook",
      "threadsAr": "Threads",
      "githubAr": "GitHub",
      "chessAr": "Chess.com",
      "steamAr": "Steam",
      "twitchAr": "Twitch",
      "xAr": "X",
      "spotifyAr": "Spotify",
      "kickAr": "Kick",
      "discordAr": "Discord",
      "discordNote": "Press to open the Discord card inside the site",
      "shareShort": "Share",
      "privacyPublic": "PUBLIC",
      "privacyPrivate": "PRIVATE",
      "quickCopyTitle": "Quick Copy",
      "steamFriendLabel": "Steam Friend Code",
      "epicGamesLabel": "Epic Games",
      "copyBtn": "Copy",
      "copied": "Copied ✓",
      "projectTitle": "Project?",
      "projectTitle2": "Demo Project",
      "projectTitle3": "The page may take a moment to load the first time",
      "projectDesc5": "Live EV dashboard with battery physics, motor simulation, WebSocket, and HUD-style telemetry.",
      "projectName": "Taamenn",
      "projectDesc": "Between the pulse of giving and the dignity of closure, development is frozen so the project remains a technical legacy.",
      "footerLine1": "Following won’t <em>electrocute you</em>",
      "footerBrand": "Omar | عُـمَر",
      "footerText1": "All rights unreserved © 2026",
      "footerText2": "Did you know all this was handmade?",
      "shareTitle": "Share Portal",
      "shareText": "Scan the code or share the link directly",
      "shareCopy": "Copy",
      "shareSend": "Share my page",
      "sharePreviewTitle": "Omar Profiles",
      "sharePreviewText": "My links, projects, and gaming codes in one clean place.",
      "shareNativeTitle": "Omar Profiles",
      "shareNativeText": "Omar's page: social links, projects, and gaming codes in one place.",
      "shared": "Share opened ✓",
      "pageTitle": "Omar Profiles",
      "ariaBtn": "Switch language to Arabic",
      "profileKicker": "Quick bio",
      "profileBio": "Tawjihi 2009 student, electrical engineering for EVs and hybrids, trying to survive the year with most brain cells intact.",
      "statusSleeping": "Sleeping",
      "statusBusy": "Busy",
      "statusOnline": "Online",
      "statusCoding": "Coding",
      "statusGaming": "Gaming",
      "copyAyah": "Copy ayah",
      "ayahCopied": "Ayah copied ✓",
      "versionLabel": "Version",
      "lowPowerOn": "Light mode enabled for this device",
      "newAyah": "New ayah",
      "badgeFeatured": "Featured",
      "badgePublic": "Public",
      "badgePrivate": "Private",
      "badgeOfficial": "Official",
      "badgeContact": "Contact",
      "versionGithub": "GitHub",
      "closeModal": "Close",
      "shareWhatsApp": "WhatsApp",
      "shareInstagram": "Instagram",
      "shareSnapchat": "Snapchat",
      "shareFallbackCopied": "Link copied. Paste it in the app you want.",
      "shareWhatsAppText": "Check Omar's page: social links, projects, and gaming codes in one place.",
      "projectVisit": "Visit project",
      "projectBack": "Back to site",
      "projectTech": "Tech",
      "projectStatus": "Status",
      "projectTaameenSummary": "Taamenn is preserved as a lightweight technical legacy from Omar's journey.",
      "projectEvSummary": "A live EV telemetry experience with direct dashboard-style indicators.",
      "projectDetails": "Project details",
      "rockstarGames": "Rockstar Games",
      "ubisoft": "Ubisoft",
      "ea": "Electronic Arts"
    }
  },
  "version": "v8.1.0 Preview • Portfolio Upgrade",
  "smartStatuses": {
    "sleeping": {
      "labelKey": "statusSleeping",
      "bg": "sleep",
      "color": "#7dd3fc",
      "glow": "rgba(125,211,252,.45)"
    },
    "busy": {
      "labelKey": "statusBusy",
      "bg": "stars",
      "color": "#f7c948",
      "glow": "rgba(247,201,72,.42)"
    },
    "online": {
      "labelKey": "statusOnline",
      "bg": "aurora",
      "color": "#27e681",
      "glow": "rgba(39,230,129,.48)"
    },
    "coding": {
      "labelKey": "statusCoding",
      "bg": "coding",
      "color": "#00eaff",
      "glow": "rgba(0,234,255,.48)"
    },
    "gaming": {
      "labelKey": "statusGaming",
      "bg": "gaming",
      "color": "#a970ff",
      "glow": "rgba(169,112,255,.50)"
    }
  }
};
