'use strict';

window.OMAR_SITE = {
  "baseUrl": "https://omar-i9.github.io/omar-i9/",
  "discordPage": "pages/discord.html",
  "titles": [
    "اهلين تعال كل يوم 👋",
    "Omar Profiles",
    "دامك رجعت شوف الباقي"
  ],
  "heroActions": [
    {
      "id": "github",
      "labelKey": "githubAr",
      "label": "GitHub",
      "icon": "fa-brands fa-github",
      "url": "https://github.com/Omar-i9"
    },
    {
      "id": "share",
      "labelKey": "shareShort",
      "label": "مشاركة",
      "icon": "fa-solid fa-share-nodes",
      "action": "share"
    },
    {
      "id": "instagram",
      "labelKey": "instagramAr",
      "label": "انستجرام",
      "icon": "fa-brands fa-instagram",
      "url": "https://www.instagram.com/omar.a.z3"
    }
  ],
  "socialLinks": [
    {
      "id": "tiktok",
      "group": "social",
      "className": "tk-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-tiktok",
      "titleKey": "tiktokAr",
      "title": "تيك توك",
      "handle": "gdmi_33",
      "url": "https://www.tiktok.com/@gdmi_33"
    },
    {
      "id": "snapchat",
      "group": "social",
      "className": "sc-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-snapchat-ghost",
      "titleKey": "snapchatAr",
      "title": "سناب شات",
      "handle": "omar-gdmi",
      "url": "https://www.snapchat.com/add/omar-gdmi"
    },
    {
      "id": "instagram",
      "group": "social",
      "className": "ig-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-instagram",
      "titleKey": "instagramAr",
      "title": "انستجرام",
      "handle": "omar.a.z3",
      "url": "https://www.instagram.com/omar.a.z3"
    },
    {
      "id": "github",
      "group": "dev",
      "className": "github-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-github",
      "titleKey": "githubAr",
      "title": "جيت هاب",
      "handle": "Omar-i9",
      "url": "https://github.com/Omar-i9"
    },
    {
      "id": "threads",
      "group": "social",
      "className": "threads-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-threads",
      "titleKey": "threadsAr",
      "title": "ثريدز",
      "handle": "@omar.a.z3",
      "url": "https://www.threads.com/@omar.a.z3"
    },
    {
      "id": "facebook",
      "group": "social",
      "className": "fb-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-facebook-f",
      "titleKey": "facebookAr",
      "title": "فيسبوك",
      "handle": "3mar.a.z3",
      "url": "https://www.facebook.com/3mar.a.z3"
    },
    {
      "id": "chess",
      "group": "gaming",
      "className": "chess-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-solid fa-chess",
      "extraBadge": "!!",
      "titleKey": "chessAr",
      "title": "شطرنج",
      "handle": "omar-g4",
      "url": "https://www.chess.com/member/omar-g4"
    },
    {
      "id": "steam",
      "group": "gaming",
      "className": "steam-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-steam",
      "titleKey": "steamAr",
      "title": "ستيم",
      "handle": "omar_gg33",
      "url": "https://steamcommunity.com/id/omar_gg33/"
    },
    {
      "id": "x",
      "group": "social",
      "className": "x-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-x-twitter",
      "titleKey": "xAr",
      "title": "اكس",
      "handle": "@OGdmi90694",
      "url": "https://x.com/OGdmi90694"
    },
    {
      "id": "spotify",
      "group": "media",
      "className": "spotify-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-spotify",
      "titleKey": "spotifyAr",
      "title": "اسبوتيفاي",
      "handle": "Omar",
      "url": "https://open.spotify.com/user/31zq4egkwu5qt6armgjuvey2tgga"
    },
    {
      "id": "kick",
      "group": "media",
      "className": "kick-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-kickstarter",
      "titleKey": "kickAr",
      "title": "كيك",
      "handle": "GDMI-3",
      "url": "https://kick.com/gdmi-3"
    },
    {
      "id": "twitch",
      "group": "media",
      "className": "twitch-card",
      "badge": "PUBLIC",
      "badgeType": "neo",
      "icon": "fa-brands fa-twitch",
      "titleKey": "twitchAr",
      "title": "تويتش",
      "handle": "GDMI3",
      "url": "https://www.twitch.tv/gdmi3"
    },
    {
      "id": "discord",
      "group": "gaming",
      "className": "ds-card",
      "badge": "PRIVATE",
      "badgeType": "vip",
      "icon": "fa-brands fa-discord",
      "titleKey": "discordAr",
      "title": "ديسكورد",
      "handleKey": "discordNote",
      "handle": "اضغط لفتح البطاقة داخل الموقع",
      "copy": "gdmi_3",
      "action": "discord"
    }
  ],
  "quickCopy": [
    {
      "labelKey": "steamFriendLabel",
      "label": "Steam Friend Code",
      "value": "1586913441"
    },
    {
      "labelKey": "epicGamesLabel",
      "label": "Epic Games",
      "value": "Omar-G4"
    }
  ],
  "projects": [
    {
      "id": "taamenn",
      "titleKey": "projectName",
      "title": "تأمين",
      "descKey": "projectDesc",
      "desc": "بين نبضِ العطاءِ ووقارِ الختام.. يُجمد التطوير ليبقى المشروعُ إرثاً تقنياً، ورمزاً لرحلةٍ اكتملت فخلدت.",
      "url": "https://omar-i9.github.io/taamenn/",
      "image": "assets/img/tameen-logo.webp",
      "status": "LEGACY"
    }
  ],
  "ayahs": [
    {
      "text": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
      "surahAr": "الفاتحة",
      "surahEn": "Al-Fatihah",
      "ayah": 5,
      "refAr": "سورة الفاتحة: 5",
      "refEn": "Surah Al-Fatihah 5",
      "en": "You alone we worship, and You alone we ask for help.",
      "noteAr": "توحيد العبادة والاستعانة.",
      "noteEn": "Worship and help belong to Allah alone.",
      "tafsirAr": "الآية تجمع أصل الطريق إلى الله: العبادة لا تُصرف إلا له، وطلب العون الحقيقي يكون منه. فيها تربية للقلب أن لا يتكبر على العبادة، ولا يثق بقوته وحدها؛ فالإنسان يعمل ويسعى، لكنه يعرف أن الثبات والتوفيق والهداية من الله.",
      "tafsirEn": "This verse gathers the heart of faith: worship belongs to Allah alone, and real help is sought from Him. It trains a person to act and strive without pretending to be self-sufficient, because guidance, strength, and steadiness ultimately come from Allah."
    },
    {
      "text": "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
      "surahAr": "البقرة",
      "surahEn": "Al-Baqarah",
      "ayah": 45,
      "refAr": "سورة البقرة: 45",
      "refEn": "Surah Al-Baqarah 45",
      "en": "Seek help through patience and prayer.",
      "noteAr": "الصبر والصلاة سند القلب.",
      "noteEn": "Patience and prayer support the heart.",
      "tafsirAr": "تدل الآية على أن مواجهة الثقل لا تكون بالاندفاع وحده، بل بالصبر الذي يثبت النفس، والصلاة التي تصل العبد بربه. الصبر هنا يشمل حبس النفس عن اليأس والمعصية، والصلاة تجدد المعنى وتعيد ترتيب القلب عندما تتزاحم الدنيا.",
      "tafsirEn": "The verse points to two supports in hardship: patience, which steadies the self, and prayer, which reconnects the servant with Allah. Patience includes resisting despair and wrongdoing, while prayer restores clarity when life becomes crowded and heavy."
    },
    {
      "text": "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
      "surahAr": "البقرة",
      "surahEn": "Al-Baqarah",
      "ayah": 153,
      "refAr": "سورة البقرة: 153",
      "refEn": "Surah Al-Baqarah 153",
      "en": "Allah is with the patient.",
      "noteAr": "معيّة الله تثبّت الصابرين.",
      "noteEn": "Allah supports the patient.",
      "tafsirAr": "المعية هنا معية عون وتأييد ورعاية، وليست مجرد علم؛ فالله عليم بكل أحد، لكنه يخص الصابرين بفضل وقوة وسكينة. الآية لا تجعل الألم جميلًا بذاته، لكنها تعطي الصابر معنى يحمله حتى لا ينهار أمام البلاء.",
      "tafsirEn": "This companionship is one of support, care, and aid. Allah knows everyone, but the patient are given special strength and calm. The verse does not make pain pleasant, but it gives hardship a meaning that keeps the heart from collapsing."
    },
    {
      "text": "فَإِنِّي قَرِيبٌ",
      "surahAr": "البقرة",
      "surahEn": "Al-Baqarah",
      "ayah": 186,
      "refAr": "سورة البقرة: 186",
      "refEn": "Surah Al-Baqarah 186",
      "en": "I am near.",
      "noteAr": "قرب الله يختصر المسافة.",
      "noteEn": "Allah's nearness opens the door of du'a.",
      "tafsirAr": "جاء الجواب مباشرًا: قريب. في الآية قرب رحمة وسمع وإجابة، وهذا يفتح باب الدعاء بلا واسطة ولا تعقيد. العبد قد يظن أن حاجته بعيدة أو صوته ضعيف، فتأتي الآية لترده إلى حقيقة أن الله يسمع ويجيب بما تقتضيه حكمته.",
      "tafsirEn": "The answer comes directly: I am near. It is nearness of mercy, hearing, and response. The verse opens the door of prayer without barriers. A person may think their need is distant or their voice is weak, but Allah hears and responds with wisdom."
    },
    {
      "text": "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
      "surahAr": "البقرة",
      "surahEn": "Al-Baqarah",
      "ayah": 286,
      "refAr": "سورة البقرة: 286",
      "refEn": "Surah Al-Baqarah 286",
      "en": "Allah does not burden a soul beyond its capacity.",
      "noteAr": "التكليف على قدر الوسع.",
      "noteEn": "Duties stay within true capacity.",
      "tafsirAr": "الآية أصل عظيم في رحمة الشريعة؛ فالله لا يطلب من العبد ما يستحيل عليه. هذا لا يعني أن الطريق دائمًا سهل، بل يعني أن ما كُلّف به الإنسان داخل حدود القدرة التي يعلمها الله، ومعها يفتح له أبواب الدعاء والاستغفار والرجوع.",
      "tafsirEn": "This verse is a major principle of mercy: Allah does not command what is impossible for a person. It does not mean life is always easy, but that duty remains within the capacity Allah knows, while repentance and prayer remain open."
    },
    {
      "text": "وَلَا تَهِنُوا وَلَا تَحْزَنُوا",
      "surahAr": "آل عمران",
      "surahEn": "Aal-Imran",
      "ayah": 139,
      "refAr": "سورة آل عمران: 139",
      "refEn": "Surah Aal-Imran 139",
      "en": "Do not weaken and do not grieve.",
      "noteAr": "لا تجعل الهزيمة تكسر المعنى.",
      "noteEn": "Pain should not break resolve.",
      "tafsirAr": "الآية تخاطب المؤمنين بعد الشدة، فتنهى عن الضعف الذي يوقف العمل، والحزن الذي يقتل العزيمة. الحزن شعور بشري، لكن المطلوب ألا يتحول إلى استسلام. الميزان أن يتعلم الإنسان من الألم ثم يقوم، لا أن يدفن نفسه تحته.",
      "tafsirEn": "The verse addresses believers after difficulty, warning against weakness that stops action and grief that kills resolve. Grief is human, but it must not become surrender. The point is to learn from pain and rise, not live buried under it."
    },
    {
      "text": "فَاعْفُ عَنْهُمْ وَاسْتَغْفِرْ لَهُمْ",
      "surahAr": "آل عمران",
      "surahEn": "Aal-Imran",
      "ayah": 159,
      "refAr": "سورة آل عمران: 159",
      "refEn": "Surah Aal-Imran 159",
      "en": "Pardon them and ask forgiveness for them.",
      "noteAr": "القوة مع الرحمة.",
      "noteEn": "Mercy is a form of strength.",
      "tafsirAr": "تأتي الآية في سياق اللين وحسن القيادة. العفو ليس ضعفًا، بل قدرة على تجاوز الخطأ مع إصلاح العلاقة. والاستغفار لهم يدل على قلب لا ينتقم لنفسه، بل يريد هداية الناس. لذلك تصنع الرحمة أثرًا لا تصنعه القسوة.",
      "tafsirEn": "The verse appears in the context of gentleness and leadership. Pardon is not weakness; it is the strength to move beyond mistakes while repairing bonds. Asking forgiveness for others shows a heart seeking guidance, not revenge."
    },
    {
      "text": "وَاصْبِرُوا إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
      "surahAr": "الأنفال",
      "surahEn": "Al-Anfal",
      "ayah": 46,
      "refAr": "سورة الأنفال: 46",
      "refEn": "Surah Al-Anfal 46",
      "en": "Be patient; Allah is with the patient.",
      "noteAr": "الثبات عند التوتر.",
      "noteEn": "Self-control protects decisions.",
      "tafsirAr": "تربط الآية الصبر بالثبات وقت الاختلاف والضغط. الصبر هنا ليس سكوتًا سلبيًا، بل ضبط للنفس حتى لا تفسد القرارات بالغضب أو العجلة. من حفظ قلبه وقت الارتباك حفظ الله له طريقه بقدرته وحكمته.",
      "tafsirEn": "This verse connects patience with steadiness under pressure. Patience is not passive silence; it is self-control so anger and haste do not ruin decisions. Whoever guards the heart in confusion is helped by Allah with wisdom and strength."
    },
    {
      "text": "قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا",
      "surahAr": "التوبة",
      "surahEn": "At-Tawbah",
      "ayah": 51,
      "refAr": "سورة التوبة: 51",
      "refEn": "Surah At-Tawbah 51",
      "en": "Say: nothing will befall us except what Allah has written for us.",
      "noteAr": "القدر يعلّم الطمأنينة.",
      "noteEn": "Destiny teaches calm after effort.",
      "tafsirAr": "الآية لا تدعو للكسل، بل للثبات بعد أخذ الأسباب. المؤمن يعمل ويخطط، ثم يعرف أن ما يقع داخل علم الله وتقديره، فلا يتحول الخوف إلى سيد عليه. الطمأنينة هنا ليست تجاهلًا للواقع، بل ثقة بالله فوق اضطراب الواقع.",
      "tafsirEn": "The verse does not call to laziness, but to steadiness after taking proper means. A believer plans and acts, then remembers that outcomes are within Allah’s knowledge and decree, so fear does not become the master."
    },
    {
      "text": "أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ",
      "surahAr": "يونس",
      "surahEn": "Yunus",
      "ayah": 62,
      "refAr": "سورة يونس: 62",
      "refEn": "Surah Yunus 62",
      "en": "Surely the allies of Allah will have no fear, nor will they grieve.",
      "noteAr": "الأمان الحقيقي في القرب من الله.",
      "noteEn": "True safety is nearness to Allah.",
      "tafsirAr": "أولياء الله هم أهل الإيمان والتقوى، لا أصحاب الدعاوى الفارغة. نفي الخوف والحزن يكون تمامه في الآخرة، وله أثر في الدنيا بالسكينة والرضا. الآية ترفع قيمة التقوى فوق كل مظاهر القوة التي يتفاخر بها الناس ثم تزول.",
      "tafsirEn": "The allies of Allah are people of faith and mindfulness, not empty claims. Complete freedom from fear and grief is in the Hereafter, while its trace appears in this life as calm and contentment. The verse raises piety above temporary displays of power."
    },
    {
      "text": "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
      "surahAr": "الرعد",
      "surahEn": "Ar-Ra'd",
      "ayah": 28,
      "refAr": "سورة الرعد: 28",
      "refEn": "Surah Ar-Ra'd 28",
      "en": "Surely, through the remembrance of Allah hearts find rest.",
      "noteAr": "الذكر يرد القلب لمركزه.",
      "noteEn": "Remembrance brings the heart back.",
      "tafsirAr": "الطمأنينة المقصودة ليست غياب المشاكل، بل استقرار القلب وهو يعرف ربه. الذكر يشمل القرآن والدعاء والتسبيح واستحضار عظمة الله. عندما يضيع الإنسان في الضجيج، يرده الذكر إلى حقيقة أكبر من الخوف والقلق.",
      "tafsirEn": "The rest mentioned here is not the absence of problems, but the heart settling through knowing its Lord. Remembrance includes Quran, prayer, glorification, and awareness of Allah. It brings the heart back from noise to a truth greater than fear."
    },
    {
      "text": "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
      "surahAr": "إبراهيم",
      "surahEn": "Ibrahim",
      "ayah": 7,
      "refAr": "سورة إبراهيم: 7",
      "refEn": "Surah Ibrahim 7",
      "en": "If you are grateful, I will surely increase you.",
      "noteAr": "الشكر سبب للزيادة.",
      "noteEn": "Gratitude is a path to increase.",
      "tafsirAr": "الشكر ليس كلمة فقط؛ هو اعتراف بالقلب، وحمد باللسان، واستعمال النعمة فيما يرضي الله. الزيادة قد تكون في المال أو البركة أو الهداية أو حفظ النعمة. الآية تجعل الامتنان عبادة عملية، لا مجرد شعور لطيف يمر وينتهي.",
      "tafsirEn": "Gratitude is not only a word; it is recognition in the heart, praise on the tongue, and using blessings in ways pleasing to Allah. Increase may come as wealth, blessing, guidance, or preservation. The verse makes gratitude a practical act of worship."
    },
    {
      "text": "فَلَنُحْيِيَنَّهُ حَيَاةً طَيِّبَةً",
      "surahAr": "النحل",
      "surahEn": "An-Nahl",
      "ayah": 97,
      "refAr": "سورة النحل: 97",
      "refEn": "Surah An-Nahl 97",
      "en": "We will surely give them a good life.",
      "noteAr": "الحياة الطيبة أثر الإيمان والعمل.",
      "noteEn": "Faith and good action bring a good life.",
      "tafsirAr": "تربط الآية الحياة الطيبة بالإيمان والعمل الصالح، للرجل والمرأة سواء. ليست الحياة الطيبة شرطًا أن تكون رفاهية كاملة، بل طمأنينة ورضا وبركة ومعنى. قد يملك الإنسان الكثير ويضيق صدره، وقد يملك القليل ويعيش بقلب واسع.",
      "tafsirEn": "The verse connects a good life to faith and righteous action for both men and women. A good life is not necessarily luxury, but peace, contentment, blessing, and meaning. A person may own much and feel narrow, or own little and live with a spacious heart."
    },
    {
      "text": "وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ",
      "surahAr": "الإسراء",
      "surahEn": "Al-Isra",
      "ayah": 70,
      "refAr": "سورة الإسراء: 70",
      "refEn": "Surah Al-Isra 70",
      "en": "We have certainly honored the children of Adam.",
      "noteAr": "الكرامة أصل للإنسان.",
      "noteEn": "Human dignity is a gift and a responsibility.",
      "tafsirAr": "تبين الآية أن للإنسان كرامة أصلية وهبها الله له، بالعقل والتسخير وحسن الخلق والقدرة على الاختيار. هذه الكرامة لا تبرر الكبر، بل توجب الشكر والمسؤولية. من عرف كرامته لم يبع نفسه للرذائل ولا ظلم غيره.",
      "tafsirEn": "The verse shows that human beings have a dignity granted by Allah through intellect, provision, and responsibility. This dignity is not a license for arrogance, but a call to gratitude and moral responsibility. Whoever knows their dignity does not degrade themselves or others."
    },
    {
      "text": "وَقُل رَّبِّ زِدْنِي عِلْمًا",
      "surahAr": "طه",
      "surahEn": "Ta-Ha",
      "ayah": 114,
      "refAr": "سورة طه: 114",
      "refEn": "Surah Ta-Ha 114",
      "en": "Say: My Lord, increase me in knowledge.",
      "noteAr": "طلب العلم عبادة.",
      "noteEn": "Beneficial knowledge is an act of worship.",
      "tafsirAr": "لم يؤمر النبي صلى الله عليه وسلم بطلب الزيادة من شيء مثل العلم. وهذا يدل على شرف العلم النافع الذي يقرب من الله ويصلح العمل. العلم ليس حفظ معلومات فقط، بل فهم يهدي السلوك ويجعل الإنسان أعدل وأبصر بنفسه وبالناس.",
      "tafsirEn": "The Prophet was commanded to ask for increase in knowledge, showing the honor of beneficial knowledge. Knowledge is not just stored information; it is understanding that guides action, brings a person nearer to Allah, and makes them more just and aware."
    },
    {
      "text": "لَا إِلَـٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
      "surahAr": "الأنبياء",
      "surahEn": "Al-Anbiya",
      "ayah": 87,
      "refAr": "سورة الأنبياء: 87",
      "refEn": "Surah Al-Anbiya 87",
      "en": "There is no god but You; glory be to You; I was among the wrongdoers.",
      "noteAr": "دعاء التوبة والافتقار.",
      "noteEn": "Repentance begins with truthfulness.",
      "tafsirAr": "هذا دعاء يونس عليه السلام في ظلمة البحر والحوت والهم. بدأ بالتوحيد والتنزيه، ثم بالاعتراف بالخطأ. قوته أنه يجمع معرفة الله ومعرفة النفس: الله كامل منزه، والعبد محتاج مقصر. لذلك كان بابًا للنجاة والرجوع.",
      "tafsirEn": "This is the prayer of Yunus in layers of darkness and distress. It begins with Allah’s oneness and perfection, then admits personal fault. Its strength is that it combines knowing Allah and knowing the self: Allah is perfect, and the servant is needy and flawed."
    },
    {
      "text": "اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
      "surahAr": "النور",
      "surahEn": "An-Nur",
      "ayah": 35,
      "refAr": "سورة النور: 35",
      "refEn": "Surah An-Nur 35",
      "en": "Allah is the Light of the heavens and the earth.",
      "noteAr": "الهداية نور من الله.",
      "noteEn": "Guidance is light from Allah.",
      "tafsirAr": "الآية من أعظم آيات النور، ومعناها أن الله منور السماوات والأرض حسًا ومعنى، وهادي أهلها. النور هنا يدل على الهداية والبيان والحياة. من لم يرزقه الله نورًا يبقى وسط الأشياء ولا يرى حقيقتها، ومن هداه الله انكشف له الطريق.",
      "tafsirEn": "This is one of the greatest verses of light. It means Allah gives light to the heavens and earth and guides their people. Light here points to guidance, clarity, and life. Without Allah’s light, a person may stand among things but not see their reality."
    },
    {
      "text": "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
      "surahAr": "العنكبوت",
      "surahEn": "Al-'Ankabut",
      "ayah": 69,
      "refAr": "سورة العنكبوت: 69",
      "refEn": "Surah Al-'Ankabut 69",
      "en": "Those who strive for Us, We will surely guide them to Our ways.",
      "noteAr": "المجاهدة تفتح أبواب الهداية.",
      "noteEn": "Sincere striving opens guidance.",
      "tafsirAr": "الهداية مرتبطة بالصدق والسعي. من جاهد نفسه في طلب الحق والعمل به، فتح الله له طرقًا من الفهم والثبات لم تكن ظاهرة له أولًا. الآية لا تعد بطريق بلا تعب، لكنها تعد بأن التعب الصادق لا يضيع عند الله.",
      "tafsirEn": "Guidance is connected to sincerity and effort. Whoever strives against the self in seeking and living the truth is opened to paths of understanding and steadiness that were not clear at first. The verse promises that sincere effort is not wasted with Allah."
    },
    {
      "text": "يَا أَيُّهَا الَّذِينَ آمَنُوا اذْكُرُوا اللَّهَ ذِكْرًا كَثِيرًا",
      "surahAr": "الأحزاب",
      "surahEn": "Al-Ahzab",
      "ayah": 41,
      "refAr": "سورة الأحزاب: 41",
      "refEn": "Surah Al-Ahzab 41",
      "en": "Believers, remember Allah with much remembrance.",
      "noteAr": "كثرة الذكر تصنع يقظة القلب.",
      "noteEn": "Frequent remembrance keeps the heart awake.",
      "tafsirAr": "الأمر بكثرة الذكر لأن القلب سريع الغفلة. الذكر الكثير لا يعني ترك الدراسة والعمل والحياة، بل أن يبقى معنى الله حاضرًا فيها. من أكثر الذكر صار قلبه أسرع رجوعًا وأقل تعلقًا بالفراغ الذي يسرق العمر بلا فائدة.",
      "tafsirEn": "The command to remember Allah often is given because the heart easily becomes heedless. Frequent remembrance does not mean abandoning study, work, or life; it means keeping awareness of Allah present within them. It makes the heart quicker to return and less attached to emptiness."
    },
    {
      "text": "أَلَيْسَ اللَّهُ بِكَافٍ عَبْدَهُ",
      "surahAr": "الزمر",
      "surahEn": "Az-Zumar",
      "ayah": 36,
      "refAr": "سورة الزمر: 36",
      "refEn": "Surah Az-Zumar 36",
      "en": "Is Allah not sufficient for His servant?",
      "noteAr": "كفاية الله تطمئن القلب.",
      "noteEn": "Allah's sufficiency calms fear.",
      "tafsirAr": "الآية تأتي بصيغة سؤال يهز الخوف: إذا كان الله كافيًا عبده، فماذا تصنع تهديدات الناس؟ الكفاية لا تلغي الأخذ بالأسباب، لكنها تمنع القلب من عبادة الأسباب. من اعتمد على الله لم يحتج أن يتكسر أمام كل خوف.",
      "tafsirEn": "The verse comes as a question that shakes fear: if Allah is sufficient for His servant, what can people’s threats truly do? This does not cancel taking means, but it prevents the heart from worshiping those means. Reliance on Allah protects the heart from breaking before every fear."
    },
    {
      "text": "لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ",
      "surahAr": "الزمر",
      "surahEn": "Az-Zumar",
      "ayah": 53,
      "refAr": "سورة الزمر: 53",
      "refEn": "Surah Az-Zumar 53",
      "en": "Do not despair of Allah’s mercy.",
      "noteAr": "باب الرحمة مفتوح للتائبين.",
      "noteEn": "Do not despair of Allah's mercy.",
      "tafsirAr": "الآية من أوسع آيات الرجاء، تنادي من أثقلته الذنوب ألا يقطع أمله من رحمة الله. القنوط خطأ لأنه يجعل الذنب أكبر في عين العبد من رحمة ربه. المطلوب ليس تبرير الخطأ، بل الرجوع الصادق والثقة بسعة المغفرة.",
      "tafsirEn": "This is one of the widest verses of hope. It calls those burdened by sins not to cut themselves off from Allah’s mercy. Despair wrongly makes the sin seem greater than the Lord’s mercy. The answer is not excusing wrong, but sincere return and trust in forgiveness."
    },
    {
      "text": "ادْعُونِي أَسْتَجِبْ لَكُمْ",
      "surahAr": "غافر",
      "surahEn": "Ghafir",
      "ayah": 60,
      "refAr": "سورة غافر: 60",
      "refEn": "Surah Ghafir 60",
      "en": "Call upon Me; I will respond to you.",
      "noteAr": "الدعاء عبادة وثقة.",
      "noteEn": "Du'a is worship and trust.",
      "tafsirAr": "الدعاء ليس آخر حل بعد فشل الخطط، بل عبادة تبدأ بها القلوب المؤمنة. الاستجابة تكون كما تقتضي حكمة الله: بإعطاء المطلوب، أو دفع شر، أو ادخار أجر. لذلك يدعو المؤمن بثقة، لا كمن يرسل كلامًا في فراغ.",
      "tafsirEn": "Prayer is not the last option after plans fail; it is worship with which believing hearts begin. Response comes according to Allah’s wisdom: granting the request, removing harm, or storing reward. So the believer calls with trust, not as if speaking into emptiness."
    },
    {
      "text": "إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا",
      "surahAr": "فصلت",
      "surahEn": "Fussilat",
      "ayah": 30,
      "refAr": "سورة فصلت: 30",
      "refEn": "Surah Fussilat 30",
      "en": "Those who say, Our Lord is Allah, then remain upright.",
      "noteAr": "الإيمان قول واستقامة.",
      "noteEn": "Faith needs uprightness.",
      "tafsirAr": "الآية تبين أن الإيمان ليس كلمة تقال ثم تترك بلا أثر؛ بل إعلان ربوبية الله ثم استقامة على أمره. الاستقامة ليست عصمة من الخطأ، لكنها رجوع دائم إلى الطريق وعدم جعل الهوى قائدًا. وبذلك تنزل السكينة والبشارة.",
      "tafsirEn": "The verse shows that faith is not a phrase without effect. It is declaring Allah as Lord, then remaining upright upon His command. Uprightness is not sinlessness, but constant return to the path and refusing to let desire become the leader. This brings calm and glad tidings."
    },
    {
      "text": "إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ",
      "surahAr": "الحجرات",
      "surahEn": "Al-Hujurat",
      "ayah": 13,
      "refAr": "سورة الحجرات: 13",
      "refEn": "Surah Al-Hujurat 13",
      "en": "The most noble of you before Allah is the most mindful of Him.",
      "noteAr": "الكرامة بالتقوى لا بالمظاهر.",
      "noteEn": "Nobility is measured by taqwa.",
      "tafsirAr": "تضع الآية ميزانًا ينسف تفاخر الناس بالأصل واللون والمال والقبيلة. معيار الكرامة عند الله هو التقوى، أي مراقبة الله والعمل بما يرضيه. هذا لا يلغي اختلاف الناس، بل يجعله للتعارف لا للتكبر والاحتقار.",
      "tafsirEn": "The verse sets a standard that overturns boasting in race, wealth, lineage, or appearance. The measure of nobility with Allah is taqwa: awareness of Him and acting in ways pleasing to Him. Human differences are for knowing one another, not arrogance or contempt."
    },
    {
      "text": "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ",
      "surahAr": "ق",
      "surahEn": "Qaf",
      "ayah": 16,
      "refAr": "سورة ق: 16",
      "refEn": "Surah Qaf 16",
      "en": "We are nearer to him than his jugular vein.",
      "noteAr": "قرب علم وإحاطة.",
      "noteEn": "Allah knows what the heart hides.",
      "tafsirAr": "الآية تذكر بإحاطة علم الله بالإنسان، حتى بما يوسوس به صدره. هذا القرب يربي الحياء والمراقبة، ويطمئن المظلوم والمهموم أن الله لا تغيب عنه خفايا القلوب. ليس الإنسان متروكًا في فوضى بلا علم ولا حساب.",
      "tafsirEn": "The verse reminds us that Allah’s knowledge surrounds the human being, even the whispers within the chest. This nearness teaches awareness and modesty before Allah, and comforts the wronged or worried: no hidden matter of the heart is absent from Him."
    },
    {
      "text": "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ",
      "surahAr": "الحديد",
      "surahEn": "Al-Hadid",
      "ayah": 4,
      "refAr": "سورة الحديد: 4",
      "refEn": "Surah Al-Hadid 4",
      "en": "He is with you wherever you are.",
      "noteAr": "معية العلم والرعاية.",
      "noteEn": "Allah is with you wherever you are.",
      "tafsirAr": "المعية هنا تدل على علم الله وإحاطته وقدرته، وأن العبد لا يخرج عن نظر ربه أينما كان. إذا فهمها القلب أورثته مراقبة في السر، وطمأنينة في الخوف، وحذرًا من أن يعيش بوجهين: وجه للناس ووجه يخفيه عن الله.",
      "tafsirEn": "This companionship indicates Allah’s knowledge, surrounding power, and care. A person is never outside the sight of the Lord. When the heart understands this, it gains awareness in private, calm in fear, and caution against living with one face for people and another hidden from Allah."
    },
    {
      "text": "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا",
      "surahAr": "الطلاق",
      "surahEn": "At-Talaq",
      "ayah": 2,
      "refAr": "سورة الطلاق: 2",
      "refEn": "Surah At-Talaq 2",
      "en": "Whoever is mindful of Allah, He will make a way out for them.",
      "noteAr": "التقوى تفتح المخارج.",
      "noteEn": "Taqwa opens a way out.",
      "tafsirAr": "الآية لا تعني أن المتقي لا يمر بضيق، بل أن الله يفتح له مخرجًا من حيث يعلم أو لا يعلم. التقوى هنا عمل حقيقي: ترك الحرام، أداء الواجب، والصدق مع الله. أحيانًا يكون المخرج حلًا، وأحيانًا يكون ثباتًا حتى يأتي الحل.",
      "tafsirEn": "The verse does not mean the mindful never face hardship. It means Allah opens a way out, known or unknown to them. Taqwa is practical: avoiding what is forbidden, fulfilling duties, and being truthful with Allah. Sometimes the way out is a solution, and sometimes it is strength until the solution comes."
    },
    {
      "text": "وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ",
      "surahAr": "الطلاق",
      "surahEn": "At-Talaq",
      "ayah": 3,
      "refAr": "سورة الطلاق: 3",
      "refEn": "Surah At-Talaq 3",
      "en": "He will provide for them from where they do not expect.",
      "noteAr": "الرزق أوسع من الحسابات الضيقة.",
      "noteEn": "Provision is wider than calculations.",
      "tafsirAr": "الرزق هنا يشمل المال والفرص والطمأنينة والعون والفتح. من اتقى الله لا يصبح خارج قوانين الدنيا، لكنه لا يبقى محبوسًا في حساباته وحدها. الله يفتح أبوابًا لم تكن في الخطة، ويصرف أشياء كان ظاهرها خيرًا وفي تركها خير أكبر.",
      "tafsirEn": "Provision includes wealth, opportunity, peace, help, and openings. Whoever has taqwa is not removed from worldly causes, but is not imprisoned by calculations alone. Allah opens doors that were not in the plan and turns away things whose absence may be a greater mercy."
    },
    {
      "text": "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ",
      "surahAr": "الضحى",
      "surahEn": "Ad-Duha",
      "ayah": 5,
      "refAr": "سورة الضحى: 5",
      "refEn": "Surah Ad-Duha 5",
      "en": "Your Lord will surely give you, and you will be pleased.",
      "noteAr": "وعد بالرضا والعطاء.",
      "noteEn": "Allah gives in the way He knows best.",
      "tafsirAr": "نزلت في تسلية النبي صلى الله عليه وسلم وتثبيت قلبه. فيها وعد كريم بأن عطاء الله يبلغ بالعبد مقام الرضا. العطاء ليس محصورًا في الدنيا؛ فقد يكون نصرًا أو هداية أو مقامًا في الآخرة. المهم أن ربك أعلم بما يرضي قلبك حقًا.",
      "tafsirEn": "The verse consoles and strengthens the Prophet. It promises that Allah’s giving will lead to satisfaction. This giving is not limited to worldly gain; it may be support, guidance, victory, or reward in the Hereafter. Your Lord knows what truly satisfies the heart."
    },
    {
      "text": "إِنَّ مَعَ الْعُسْرِ يُسْرًا",
      "surahAr": "الشرح",
      "surahEn": "Ash-Sharh",
      "ayah": 6,
      "refAr": "سورة الشرح: 6",
      "refEn": "Surah Ash-Sharh 6",
      "en": "Indeed, with hardship comes ease.",
      "noteAr": "اليسر مرافق للعسر.",
      "noteEn": "Ease can begin within hardship.",
      "tafsirAr": "تكرار معنى اليسر في السورة يزيد اليقين بأن الشدة ليست أبدية. كلمة مع تفيد أن اليسر قد يبدأ داخل العسر لا بعده فقط: سكينة، فهم، صديق صادق، أو باب صغير يفتح. المؤمن لا ينكر الألم، لكنه لا يراه نهاية القصة.",
      "tafsirEn": "The repeated meaning of ease in the surah strengthens certainty that hardship is not permanent. The word with suggests ease may begin inside hardship, not only after it: calm, understanding, a truthful friend, or a small opening. The believer does not deny pain, but does not see it as the end."
    }
  ],
  "translations": {
    "ar": {
      "heroName": "عُـمَر | Omar",
      "heroDesc": "دامك دخلت كمل معروفك وشوف الباقي..!",
      "langHint": "تغيير اللغة",
      "ayahPill": "آية",
      "ayahHint": "اضغط لعرض تفاصيل الآية",
      "showAyah": "إظهار الآية",
      "hideAyah": "إخفاء الآية",
      "socialLinksTitle": "روابط التواصل",
      "instagramAr": "انستجرام",
      "snapchatAr": "سناب شات",
      "tiktokAr": "تيك توك",
      "facebookAr": "فيسبوك",
      "threadsAr": "ثريدز",
      "githubAr": "جيت هاب",
      "chessAr": "شطرنج",
      "steamAr": "ستيم",
      "twitchAr": "تويتش",
      "xAr": "اكس",
      "spotifyAr": "اسبوتيفاي",
      "kickAr": "كيك",
      "discordAr": "ديسكورد",
      "discordNote": "اضغط لفتح البطاقة داخل الموقع",
      "shareShort": "مشاركة",
      "privacyPublic": "عام",
      "privacyPrivate": "خاص",
      "quickCopyTitle": "نسخ سريع",
      "steamFriendLabel": "Steam Friend Code",
      "epicGamesLabel": "Epic Games",
      "copyBtn": "نسخ",
      "copied": "تم النسخ ✓",
      "projectTitle": "مشروع؟",
      "projectTitle2": "مشروع نسخه تجريبية",
      "projectTitle3": "قد يستغرق وقت لتحميل الصفحة لاول مرة",
      "projectDesc5": "لوحة تحكم حية لسيارة كهربائية — فيزياء بطارية ومحرك حقيقية، WebSocket، HUD احترافي.",
      "projectName": "تأمين",
      "projectDesc": "بين نبضِ العطاءِ ووقارِ الختام.. يُجمد التطوير ليبقى المشروعُ إرثاً تقنياً، ورمزاً لرحلةٍ اكتملت فخلدت.",
      "footerLine1": "الفولو <em>ما بكهربك</em>",
      "footerBrand": "عُـمَر | Omar",
      "footerText1": "جميع الحقوق غير محفوظة © 2026",
      "footerText2": "بتعرف انه كل هاد شغل ايدي؟",
      "shareTitle": "بوابة المشاركة",
      "shareText": "امسح الكود أو شارك الرابط مباشرة",
      "shareCopy": "نسخ",
      "shareSend": "إرسال رابط صفحاتي",
      "sharePreviewTitle": "صفحات عمر",
      "sharePreviewText": "كل حساباتي ومشاريعي وكلشي بمكان واحد.",
      "shareNativeTitle": "صفحات عمر | Omar Profiles",
      "shareNativeText": "صفحة عمر: روابط التواصل، المشاريع وكلشي في مكان واحد.",
      "shared": "تم فتح المشاركة ✓",
      "pageTitle": "Omar Profiles",
      "ariaBtn": "تبديل اللغة إلى الإنجليزية",
      "profileKicker": "نبذة سريعة",
      "profileBio": "طالب توجيهي 2009، هندسة كهربائية للسيارات الكهربائية والهايبرد، وبحاول أطلع من السنة بعقلي كامل.",
      "statusSleeping": "نائم",
      "statusBusy": "مشغول",
      "statusOnline": "متصل",
      "statusCoding": "يبرمج",
      "statusGaming": "يلعب",
      "copyAyah": "نسخ الآية",
      "ayahCopied": "تم نسخ الآية ✓",
      "versionLabel": "الإصدار",
      "lowPowerOn": "تم تفعيل الوضع الخفيف للجهاز"
    },
    "en": {
      "heroName": "Omar | عُـمَر",
      "heroDesc": "Since you came in, keep going and check the rest..!",
      "langHint": "Change language",
      "ayahPill": "Ayah",
      "ayahHint": "Tap to view tafsir",
      "showAyah": "Show ayah",
      "hideAyah": "Hide ayah",
      "socialLinksTitle": "Social Links",
      "instagramAr": "Instagram",
      "snapchatAr": "Snapchat",
      "tiktokAr": "TikTok",
      "facebookAr": "Facebook",
      "threadsAr": "Threads",
      "githubAr": "GitHub",
      "chessAr": "Chess.com",
      "steamAr": "Steam",
      "twitchAr": "Twitch",
      "xAr": "X",
      "spotifyAr": "Spotify",
      "kickAr": "Kick",
      "discordAr": "Discord",
      "discordNote": "Press to open the Discord card inside the site",
      "shareShort": "Share",
      "privacyPublic": "PUBLIC",
      "privacyPrivate": "PRIVATE",
      "quickCopyTitle": "Quick Copy",
      "steamFriendLabel": "Steam Friend Code",
      "epicGamesLabel": "Epic Games",
      "copyBtn": "Copy",
      "copied": "Copied ✓",
      "projectTitle": "Project?",
      "projectTitle2": "Demo Project",
      "projectTitle3": "The page may take a moment to load the first time",
      "projectDesc5": "Live EV dashboard with battery physics, motor simulation, WebSocket, and HUD-style telemetry.",
      "projectName": "Taamenn",
      "projectDesc": "Between the pulse of giving and the dignity of closure, development is frozen so the project remains a technical legacy.",
      "footerLine1": "Following won’t <em>electrocute you</em>",
      "footerBrand": "Omar | عُـمَر",
      "footerText1": "All rights unreserved © 2026",
      "footerText2": "Did you know all this was handmade?",
      "shareTitle": "Share Portal",
      "shareText": "Scan the code or share the link directly",
      "shareCopy": "Copy",
      "shareSend": "Share my page",
      "sharePreviewTitle": "Omar Profiles",
      "sharePreviewText": "My links, projects and everything in one clean place.",
      "shareNativeTitle": "Omar Profiles",
      "shareNativeText": "Omar's page: social links, projects and everything in one place.",
      "shared": "Share opened ✓",
      "pageTitle": "Omar Profiles",
      "ariaBtn": "Switch language to Arabic",
      "profileKicker": "Quick bio",
      "profileBio": "Tawjihi 2009 student, electrical engineering for EVs and hybrids, trying to survive the year with most brain cells intact.",
      "statusSleeping": "Sleeping",
      "statusBusy": "Busy",
      "statusOnline": "Online",
      "statusCoding": "Coding",
      "statusGaming": "Gaming",
      "copyAyah": "Copy ayah",
      "ayahCopied": "Ayah copied ✓",
      "versionLabel": "Version",
      "lowPowerOn": "Light mode enabled for this device"
    }
  },
  "version": "v6.0 • Smart Polish",
  "smartStatuses": {
    "sleeping": {
      "labelKey": "statusSleeping",
      "bg": "sleep",
      "color": "#7dd3fc",
      "glow": "rgba(125,211,252,.45)"
    },
    "busy": {
      "labelKey": "statusBusy",
      "bg": "stars",
      "color": "#f7c948",
      "glow": "rgba(247,201,72,.42)"
    },
    "online": {
      "labelKey": "statusOnline",
      "bg": "aurora",
      "color": "#27e681",
      "glow": "rgba(39,230,129,.48)"
    },
    "coding": {
      "labelKey": "statusCoding",
      "bg": "coding",
      "color": "#00eaff",
      "glow": "rgba(0,234,255,.48)"
    },
    "gaming": {
      "labelKey": "statusGaming",
      "bg": "gaming",
      "color": "#a970ff",
      "glow": "rgba(169,112,255,.50)"
    }
  }
};
